from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="books_index"),
    path('list_books/', views.list_books, name="books_list_books"),
    path('<int:bookId>/', views.viewbook, name="books_view_one_book"),
    path('aboutus/', views.aboutus, name="books_aboutus"),
    path('html5/links/', views.links),
    path('html5/text/formatting/', views.formatting),
    path('html5/listing/', views.listing),
    path('html5/tables/', views.tables),
    path('search', views.search, name='search'),
    path('lab8/task1', views.lab8_task1),
    path('lab8/task2', views.lab8_task2),
    path('lab8/task3', views.lab8_task3),
    path('lab8/task4', views.lab8_task4),
    path('lab8/task5', views.lab8_task5),
    path('lab8/task7', views.lab8_task7),
    path('lab9/task1', views.lab9_task1, name='lab9_task1'),
    path('lab9/task2', views.lab9_task2, name='lab9_task2'),
    path('lab9/task3', views.lab9_task3, name='lab9_task3'),
    path('lab9/task4', views.lab9_task4, name='lab9_task4'),
    path('lab9/task5', views.lab9_task5, name='lab9_task5'),
    path('lab9/task6', views.lab9_task6, name='lab9_task6'),
    path('lab9_part1/listbooks', views.list_books, name='list_books'),
    path('lab9_part1/addbook', views.add_book, name='add_book'),
    path('lab9_part1/editbook/<int:id>', views.edit_book, name='edit_book'),
    path('lab9_part1/deletebook/<int:id>', views.delete_book, name='delete_book'),
    path('lab9_part2/listbooks', views.list_books2, name='list_books2'),
    path('lab9_part2/addbook', views.add_book2, name='add_book2'),
    path('lab9_part2/editbook/<int:id>', views.edit_book2, name='edit_book2'),
    path('lab9_part2/deletebook/<int:id>', views.delete_book2, name='delete_book2'),
]
